# version: '3.8'

# services:
#   sqlserver:
#     image: mcr.microsoft.com/mssql/server:2019-latest
#     container_name: sqlserver2019
#     environment:
#       ACCEPT_EULA: "Y"
#       SA_PASSWORD: "Computo.123"   # Cámbiala por una segura
#     ports:
#       - "1433:1433"
#     volumes:
#       - sqlserver_data:/var/opt/mssql

#   api:
#     build:
#       context: .
#       dockerfile: src/MyFinance.API/Dockerfile
#     image: myfinance-api:latest
#     container_name: myfinance-api
#     depends_on:
#       - sqlserver
#     environment:
#       # Cadena de conexión apuntando al servicio 'sqlserver'
#       ConnectionStrings__DefaultConnection: |
#         Server=sqlserver,1433;
#         Database=MyFinanceDb;
#         User Id=sa;
#         Password=Computo.123;
#     ports:
#       - "5000:80"

#   client:
#     build:
#       context: .
#       dockerfile: src/Myfinance.Client/Dockerfile
#     image: myfinance-client:latest
#     container_name: myfinance-client
#     depends_on:
#       - api
#     ports:
#       - "5001:80"

# volumes:
#   sqlserver_data:
version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: myfinance-db
    environment:
      SA_PASSWORD: "Computo.123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  api:
    build: .
    container_name: myfinance-api
    ports:
      - "5000:80"               # Exponer puerto 5000 en host → 80 en contenedor
      - "5001:443"               # Exponer puerto 5001 en host → 443 en contenedor
    environment:
      ASPNETCORE_URLS: "http://+:80;https://+:443"
      # La cadena de conexión apunta al servicio 'db'
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=MyFinanceDb;User Id=sa;Password=Computo.123;TrustServerCertificate=True;"
    depends_on:
      - db
